;;; -*- lexical-binding: t; use-package-always-ensure: t; -*-

(eval-and-compile (require 'utility-fns))

(message-load-file)

(global-set-key (kbd "C-c m")
                (if (eq system-type 'darwin)
                    'toggle-frame-fullscreen
                  'toggle-frame-maximized))
(add-to-list 'default-frame-alist (cons
                                   'fullscreen
                                   (if (eq system-type 'darwin)
                                       'fullboth
                                     'maximized)))

;;; cl-base16 stuff
;; code to load a theme generated by github.com/tpine/cl-base16
;;
;; there's an elisp package do generate and use the themes at
;; github.com/belak/base16-emacs, but i'm already using cl-base16 to
;; support base16-stumpwm. i didn't see any reason to have both of
;; them build themes (which is slow), so i have cl-base16 responsible
;; for building my themes, and i have emacs load them manually as
;; follows

(defvar *cl-base16-emacs-template* "/home/phoebe/quicklisp/local-projects/cl-base16/sources/templates/emacs/")
(defvar *cl-base16-emacs-themes* (concat *cl-base16-emacs-template* "build/"))

(when (and (file-directory-p *cl-base16-emacs-template*)
           (file-directory-p *cl-base16-emacs-themes*))
  ;; so the theme can (require 'base16-theme)
  (add-to-list 'load-path *cl-base16-emacs-template*)
  ;; so emacs knows where to find the theme
  (add-to-list 'custom-theme-load-path *cl-base16-emacs-themes*)
  ;; my theme of choice
  (load-theme 'base16-dracula))

(provide 'window-settings)
